// This file was automatically generated by informer-gen

package v1alpha1

import (
	time "time"

	tagcontroller_v1alpha1 "github.com/mjudeikis/ocp-controller/pkg/apis/tagcontroller/v1alpha1"
	versioned "github.com/mjudeikis/ocp-controller/pkg/tagcontroller/clientset/versioned"
	internalinterfaces "github.com/mjudeikis/ocp-controller/pkg/tagcontroller/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/mjudeikis/ocp-controller/pkg/tagcontroller/listers/tagcontroller/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// TagInformer provides access to a shared informer and lister for
// Tags.
type TagInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.TagLister
}

type tagInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewTagInformer constructs a new informer for Tag type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewTagInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredTagInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredTagInformer constructs a new informer for Tag type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredTagInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeploymentsV1alpha1().Tags(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.DeploymentsV1alpha1().Tags(namespace).Watch(options)
			},
		},
		&tagcontroller_v1alpha1.Tag{},
		resyncPeriod,
		indexers,
	)
}

func (f *tagInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredTagInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *tagInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&tagcontroller_v1alpha1.Tag{}, f.defaultInformer)
}

func (f *tagInformer) Lister() v1alpha1.TagLister {
	return v1alpha1.NewTagLister(f.Informer().GetIndexer())
}
