// This file was automatically generated by lister-gen

package v1alpha1

// FooListerExpansion allows custom methods to be added to
// FooLister.
type FooListerExpansion interface{}

// FooNamespaceListerExpansion allows custom methods to be added to
// FooNamespaceLister.
type FooNamespaceListerExpansion interface{}
