// This file was automatically generated by lister-gen

package v1alpha1

// TagListerExpansion allows custom methods to be added to
// TagLister.
type TagListerExpansion interface{}

// TagNamespaceListerExpansion allows custom methods to be added to
// TagNamespaceLister.
type TagNamespaceListerExpansion interface{}
